type Gateway {
    id: ID!
    name: String
    description: String
    manufacturer: String
    model: String
    serialNumber: String
    softwareVersion: String
    auth: Auth
    features: [Feature!]
}

type Device {
    id: ID!
    name: String
    description: String
    manufacturer: String
    model: String
    serialNumber: String
    softwareVersion: String
    location: Location
    features: [Feature!]
}

interface Feature {
    id: ID!
    name: String
    description: String
    settable: Boolean!
}

type IntFeature implements Feature {
    id: ID!
    name: String
    description: String
    settable: Boolean!
    valueUnitPrefix: UnitPrefix
    valueUnit: Unit
    valueMin: Int
    valueMax: Int
    readingValue: Int
    readingDateTime: DateTime
    settingValue: Int
    settingDateTime: DateTime
}

type FloatFeature implements Feature {
    id: ID!
    name: String
    description: String
    settable: Boolean!
    valueUnitPrefix: UnitPrefix
    valueUnit: Unit
    valueMin: Float
    valueMax: Float
    readingValue: Float
    readingDateTime: DateTime
    settingValue: Float
    settingDateTime: DateTime
}

type BooleanFeature implements Feature {
    id: ID!
    name: String
    description: String
    settable: Boolean!
    readingValue: Boolean
    readingDateTime: DateTime
    settingValue: Boolean
    settingDateTime: DateTime
}

type StringFeature implements Feature {
    id: ID!
    name: String
    description: String
    settable: Boolean!
    valueOptions:  [String!]
    readingValue: String
    readingDateTime: DateTime
    settingValue: String
    settingDateTime: DateTime
}

type Location {
    id: ID!
    name: String
    description: String
    parent: Location
}

type Auth {
    id: ID!
    username: String!
    password: String!
    protocols: [Protocol!]!
    listenOn: String
    reportOn: String
    created: DateTime
    updated: DateTime
}

enum Protocol {
    AMQP
    MQTT
    STOMP
}

enum UnitPrefix {
    # METRIC
    YOTTA
    ZETTA
    EXA
    PETA
    TERA
    GIGA
    MEGA
    KILO
    HECTO
    DECA
    DECI
    CENTI
    MILLI
    MICRO
    NANO
    PICO
    FEMTO
    ATTO
    ZEPTO
    YOCTO

    # BINARY
    KIBI
    MEBI
    GIBI
    TEBI
    PEBI
    EXBI
    ZEBI
    YOBI

    # GEOMETRIC
    SQUARE
    CUBIC
}

enum Unit {
    # MASS/WEIGHT
    GRAM
    POUND
    OUNCE

    # VOLUME
    LITER
    US_GALLON
    IMP_GALLON
    US_PINT
    IMP_PINT
    US_FLUID_OUNCE
    IMP_FLUID_OUNCE

    # LENGTH
    METER
    INCH
    FOOT
    YARD
    MILE
    NAUTICAL_MILE 

    # TIME
    SECOND

    # ANGLE
    RADION
    DEGREE

    # TEMPERATURE
    KELVIN # officially this is not "degree kelvin"
    DEGREE_CELSIUS
    DEGREE_FAHRENHEIT

    # ENERGY
    JOULE
    WATT_HOUR
    CALORIE

    # DATA
    BIT
    BYTE
}

"""RFC 3339 datetime value (https://tools.ietf.org/html/rfc3339)"""
scalar DateTime
